/* Generated by Yosys 0.56+30 (git sha1 fb024c4d5, g++ 11.4.0-1ubuntu1~22.04 -fPIC -O3) */

module \$paramod\counter\WIDTH=s32'00000000000000000000000000001000 (clk, rst_n, en, q);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input en;
  wire en;
  output [7:0] q;
  wire [7:0] q;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire [7:0] _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  INV_X1 _31_ (
    .A(_23_[0]),
    .ZN(_08_)
  );
  INV_X1 _32_ (
    .A(rst_n),
    .ZN(_09_)
  );
  NOR2_X1 _33_ (
    .A1(en),
    .A2(q[0]),
    .ZN(_10_)
  );
  AOI211_X1 _34_ (
    .A(_09_),
    .B(_10_),
    .C1(en),
    .C2(_08_),
    .ZN(_00_)
  );
  AND3_X1 _35_ (
    .A1(en),
    .A2(q[1]),
    .A3(q[0]),
    .ZN(_11_)
  );
  AOI21_X1 _36_ (
    .A(q[1]),
    .B1(q[0]),
    .B2(en),
    .ZN(_12_)
  );
  NOR3_X1 _37_ (
    .A1(_09_),
    .A2(_11_),
    .A3(_12_),
    .ZN(_01_)
  );
  AND4_X1 _38_ (
    .A1(en),
    .A2(q[2]),
    .A3(q[1]),
    .A4(q[0]),
    .ZN(_13_)
  );
  OAI21_X1 _39_ (
    .A(rst_n),
    .B1(_11_),
    .B2(q[2]),
    .ZN(_14_)
  );
  NOR2_X1 _40_ (
    .A1(_13_),
    .A2(_14_),
    .ZN(_02_)
  );
  AND2_X1 _41_ (
    .A1(q[3]),
    .A2(_13_),
    .ZN(_15_)
  );
  OAI21_X1 _42_ (
    .A(rst_n),
    .B1(_13_),
    .B2(q[3]),
    .ZN(_16_)
  );
  NOR2_X1 _43_ (
    .A1(_15_),
    .A2(_16_),
    .ZN(_03_)
  );
  OAI21_X1 _44_ (
    .A(rst_n),
    .B1(_15_),
    .B2(q[4]),
    .ZN(_17_)
  );
  AOI21_X1 _45_ (
    .A(_17_),
    .B1(_15_),
    .B2(q[4]),
    .ZN(_04_)
  );
  AND4_X1 _46_ (
    .A1(q[5]),
    .A2(q[4]),
    .A3(q[3]),
    .A4(_13_),
    .ZN(_18_)
  );
  AOI21_X1 _47_ (
    .A(q[5]),
    .B1(q[4]),
    .B2(_15_),
    .ZN(_19_)
  );
  NOR3_X1 _48_ (
    .A1(_09_),
    .A2(_18_),
    .A3(_19_),
    .ZN(_05_)
  );
  OAI21_X1 _49_ (
    .A(rst_n),
    .B1(_18_),
    .B2(q[6]),
    .ZN(_20_)
  );
  AOI21_X1 _50_ (
    .A(_20_),
    .B1(_18_),
    .B2(q[6]),
    .ZN(_06_)
  );
  AND3_X1 _51_ (
    .A1(q[7]),
    .A2(q[6]),
    .A3(_18_),
    .ZN(_21_)
  );
  AOI21_X1 _52_ (
    .A(q[7]),
    .B1(q[6]),
    .B2(_18_),
    .ZN(_22_)
  );
  NOR3_X1 _53_ (
    .A1(_09_),
    .A2(_21_),
    .A3(_22_),
    .ZN(_07_)
  );
  DFF_X1 _54_ (
    .CK(clk),
    .D(_00_),
    .Q(q[0]),
    .QN(_23_[0])
  );
  DFF_X1 _55_ (
    .CK(clk),
    .D(_01_),
    .Q(q[1]),
    .QN(_30_)
  );
  DFF_X1 _56_ (
    .CK(clk),
    .D(_02_),
    .Q(q[2]),
    .QN(_29_)
  );
  DFF_X1 _57_ (
    .CK(clk),
    .D(_03_),
    .Q(q[3]),
    .QN(_28_)
  );
  DFF_X1 _58_ (
    .CK(clk),
    .D(_04_),
    .Q(q[4]),
    .QN(_27_)
  );
  DFF_X1 _59_ (
    .CK(clk),
    .D(_05_),
    .Q(q[5]),
    .QN(_26_)
  );
  DFF_X1 _60_ (
    .CK(clk),
    .D(_06_),
    .Q(q[6]),
    .QN(_25_)
  );
  DFF_X1 _61_ (
    .CK(clk),
    .D(_07_),
    .Q(q[7]),
    .QN(_24_)
  );
  assign _23_[7:1] = q[7:1];
endmodule

module top(clk, rst_n, en, q);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input en;
  wire en;
  output [7:0] q;
  wire [7:0] q;
  \$paramod\counter\WIDTH=s32'00000000000000000000000000001000  u_cnt (
    .clk(clk),
    .en(en),
    .q(q),
    .rst_n(rst_n)
  );
endmodule
